//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Budget changes not saved.
        /// </summary>
        internal static string AddEditBudgetFailed {
            get {
                return ResourceManager.GetString("AddEditBudgetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Expense changes not saved.
        /// </summary>
        internal static string AddEditExpenseFailed {
            get {
                return ResourceManager.GetString("AddEditExpenseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Goal changes not saved.
        /// </summary>
        internal static string AddEditGoalFailed {
            get {
                return ResourceManager.GetString("AddEditGoalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Income changes not saved.
        /// </summary>
        internal static string AddEditIncomeFailed {
            get {
                return ResourceManager.GetString("AddEditIncomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Authentication failed. Try again.
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Budget has not been deleted.
        /// </summary>
        internal static string DeleteBudgetFailed {
            get {
                return ResourceManager.GetString("DeleteBudgetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Expense has not been deleted.
        /// </summary>
        internal static string DeleteExpenseFailed {
            get {
                return ResourceManager.GetString("DeleteExpenseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Goal has not been deleted.
        /// </summary>
        internal static string DeleteGoalFailed {
            get {
                return ResourceManager.GetString("DeleteGoalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Income has not been deleted.
        /// </summary>
        internal static string DeleteIncomeFailed {
            get {
                return ResourceManager.GetString("DeleteIncomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Differences not received.
        /// </summary>
        internal static string GetDifferenceFailed {
            get {
                return ResourceManager.GetString("GetDifferenceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Planned expenses and incomes not received.
        /// </summary>
        internal static string GetPlannedIncomesExpensesFailed {
            get {
                return ResourceManager.GetString("GetPlannedIncomesExpensesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Budgets not received.
        /// </summary>
        internal static string GetUserBudgetsFailed {
            get {
                return ResourceManager.GetString("GetUserBudgetsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Expenses not received.
        /// </summary>
        internal static string GetUserExpensesFailed {
            get {
                return ResourceManager.GetString("GetUserExpensesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Goals not received.
        /// </summary>
        internal static string GetUserGoalsFailed {
            get {
                return ResourceManager.GetString("GetUserGoalsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Incomes not received.
        /// </summary>
        internal static string GetUserIncomesFailed {
            get {
                return ResourceManager.GetString("GetUserIncomesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Null expense types.
        /// </summary>
        internal static string NullExpenseTypes {
            get {
                return ResourceManager.GetString("NullExpenseTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Null income types.
        /// </summary>
        internal static string NullIncomeTypes {
            get {
                return ResourceManager.GetString("NullIncomeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Null time periods.
        /// </summary>
        internal static string NullTimePeriods {
            get {
                return ResourceManager.GetString("NullTimePeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail: Register failed. Try again.
        /// </summary>
        internal static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password isn&apos;t valid.
        /// </summary>
        internal static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
